### ISSUE TITLE
Quest 2 issue, with audio device

### ISSUE THREAD

**Issue by knightwindbass** [lucoiso/UESpeechGPT#5]
Hi there, i am trying to use it, in a oculus quest 2 apk, but when i press de microphone it close the apk. Im guessing is something with the audio record device, or some error cause the azure service. Cause when i run it in the pc preview or android preview, even vr preview it works. But in the devices crash it. By the way thanks a lot, it a great job  and a nice idea.

**Comment by lucoiso** [comment]
Hello @knightwindbass ! :)
Sorry for the delay.

Are you packaging for android in shipping mode? 

There's currently an issue occurring with AzSpeech (I think it's an internal bug with Unreal Engine) that is causing the third-party libraries to not be included in the packaged project.
This doesn't occur with other engine versions and also doesn't occur when packaging in Development or Debug Game mode. :S

Can you try packaging in development mode? You can also check if the audio device is valid and get all available audio devices with: Is Audio Input Device Available & Get Available Audio Input Devices.

**Comment by knightwindbass** [comment]
Thanks, yeah i was packaging in shipping mode. I use the voice sdk before and it works when i put a external microphone in the Quest 2. But i think you´re right  it could be an internal bug with unreal. Thanks, i will make you know if i found something.
