### ISSUE TITLE
Error when trying to open project.

### ISSUE THREAD

**Issue by FR33K1LL** [lucoiso/UESpeechGPT#6]
I am unable to open the project file. This is the error I receive.

While compiling C:\Users\S\Desktop\UESpeechGPT-main\UESpeechGPT-main\Intermediate\Build\BuildRules\SpeechGPTModuleRules.dll:
c:\Users\S\Desktop\UESpeechGPT-main\UESpeechGPT-main\Source\SpeechGPT.Target.cs(14,3) : error CS0103: The name 'IncludeOrderVersion' does not exist in the current context
c:\Users\S\Desktop\UESpeechGPT-main\UESpeechGPT-main\Source\SpeechGPT.Target.cs(14,25) : error CS0103: The name 'EngineIncludeOrderVersion' does not exist in the current context
c:\Users\S\Desktop\UESpeechGPT-main\UESpeechGPT-main\Source\SpeechGPTEditor.Target.cs(14,3) : error CS0103: The name 'IncludeOrderVersion' does not exist in the current context
c:\Users\S\Desktop\UESpeechGPT-main\UESpeechGPT-main\Source\SpeechGPTEditor.Target.cs(14,25) : error CS0103: The name 'EngineIncludeOrderVersion' does not exist in the current context
ERROR: Unable to compile source files.

**Comment by lucoiso** [comment]
Hello @FR33K1LL and sorry for the delay! :)

IncludeOrderVersion & EngineIncludeOrderVersion are available for UE5.1+

This project was built in Unreal Engine 5.1, make sure you're using this version or a newer one.

If this issue is still occurring, feel free to contact! :)
