### ISSUE TITLE
Error calls the text to soundwave

### ISSUE THREAD

**Issue by knightwindbass** [lucoiso/UESpeechGPT#7]
Hi there, i update the version to the last one, and i am getting now this error on the output log, not always happen, but too often.

LogHttpGPT: Display: SetReadyToDestroy (288605): Setting task as Ready to Destroy
LogAzSpeech: Display: Task: TextToSoundWave (275926); Function: Activate; Message: Activating task
LogAzSpeech: Error: Task: TextToSoundWave (275926); Function: Activate; Message: Failed to activate task
LogAzSpeech: Display: Task: TextToSoundWave (275926); Function: SetReadyToDestroy; Message: Setting task as Ready to Destroy

Maybe you have an idea, about what is happening. 

For what i see, its cause there is no text, and i guess it was a miss understanding in my code. Now i fix it, and it works fine. By the way thanks for de Main Map for debug.

**Comment by lucoiso** [comment]
Hello! Can you enable the internal & SDK logs and send me the log files?

You can enable them in Project Settings -> Plugins -> AzSpeech -> Information -> Enable Internal Logs & Enable Azure SDK Logs
Logs are generated in PROJECT_DIRECTORY/Saved/Logs and PROJECT_DIRECTORY/Saved/Logs/AzSpeech

My email: contatolukevboas@gmail.com

**Comment by knightwindbass** [comment]
Thanks, i will send you but i guess i found my problem, i activate the log, and at least by the way i am using the plugin, the problem was that the response text was empty and when i call the function text to speach there was nothing to convert. What I found a problem cause i reach the top of tokens between context, response and promt, i guess, that is cause in the assistent chat text box i just get no text content more than the symbol {

I see there is a new update. Great support man..
