### ISSUE TITLE
Covert speech to OpenAI prompt is not working.Would you like to help?

### ISSUE THREAD

**Issue by jinskanna** [lucoiso/UESpeechGPT#8]
![image](https://user-images.githubusercontent.com/20239634/235409347-76a767b6-a0e9-44d3-b630-e004b988cc82.png)
node is above like this,I am not sure is that right or not.

Your UESpeechGPT project can't running on my computer so I can not see the logic of your blueprint

Waiting for your answer thanks again and have a good day

**Comment by lucoiso** [comment]
Hello! Looks like a different plugin! :)

Can you ensure that you're using HttpGPT? The funtions used to send messages via HttpGPT are:
* Send Message with Default Options
* Send Messages with Default Options
* Send Message with Custom Options
* Send Messages with Custom Options
